### ISSUE TITLE
Act 4 keys suggestion.

### ISSUE THREAD

**Issue by Jazzer360** [erasels/mintySpire#13]
Here's a suggestion related to the keys for act 4:

Highlight recall when you're at the last campfire before the act 3 boss.

Highlight the sapphire key when you're at the last guaranteed chest in the run. Possibly indicate before opening for the times when you have cursed key and would otherwise skip the chest.

Highlight the super-elite in act 3 if you don't already have the emerald key.

I've accidentally missed out on act 4 because I wasn't paying close enough attention to picking up the keys for it.

**Comment by erasels** [comment]
A mod for this already exists, it's called key reminder
