### ISSUE TITLE
Awakened Dab

### ISSUE THREAD

**Issue by mriswithe** [erasels/mintySpire#7]
I had no idea that Awakened one dabbed, thought you would enjoy these. Not a problem, just funny:

https://clips.twitch.tv/FancyFitPenguinSSSsss

Then this one happened after several turns of waiting for it to happen again:

https://clips.twitch.tv/HotSullenDotterelHoneyBadger

**Comment by erasels** [comment]
Thank you, I love seeing these reactions!
